### ISSUE TITLE
[REST API] Events got lost sometimes

### ISSUE THREAD

**Issue by unext-wendong** [treasure-data/td-android-sdk#27]
This is not directly related to td-android-sdk. If it's not appropriate to report it here, please let me know where I should go to. Thanks.

I'm trying to use TD's REST API directly on my Android application. The REST API I'm using is from:
https://docs.treasuredata.com/articles/rest-api-import
I'm using the POST API.

The problem is that if I sent two events within a short period, e.g. 3 or 5 seconds, then one of them got lost, even if I received return code 200 from the API for both events. By lost, I mean the event is not pushed into my database.

Sometimes I even observed that both of the events got lost.

Is this a known issue? Or I'm using the API in a wrong way?

Thanks,

**Comment by unext-wendong** [comment]
Observed same behavior on td-android-sdk, which uses REST API:
```
<td-endpoint>/android/v3/event
```

If the app calls `TreasureData.sharedInstance().uploadEvents()` twice in a short period, e.g. 20 seconds, the events in the second upload might not be synced to the backend db, even if the log indicates that both uploads succeeded, like following:
```
08-01 11:31:12.905  8383  8402 I TDLogging: Received response: '{"my_db.my_table":[{"success":true}]}' (200)
...
08-01 11:31:32.551  8383  8402 I TDLogging: Received response: '{"my_db.my_table":[{"success":true}]}' (200)
```

From the test using:
```
<td-endpoint>/postback/v3/event
```
Only if the interval between two invocations is larger than 10 minutes, both events got synced to the db.

Is this a limitation of TreasureData's endpoint server?
Can anyone from TreasureData make a comment? It'll be very helpful.

Thanks,

**Comment by komamitsu** [comment]
> Is this a limitation of TreasureData's endpoint server?

Right. The endpoint servers that handle requests from Android / iOS / Unity / JavaScript and so one buffer many fine requests for several minutes to make the throughput better.

**Comment by unext-wendong** [comment]
@komamitsu 

Thanks for the quick response. Really appreciated.

> so one buffer many fine requests for several minutes to make the throughput better.

Understand and agree.

Another issue seems to be that the API doesn't give an accurate feedback on whether the request has been served successfully or not. If the server is being busy and couldn't serve the new coming requests, wouldn't it be good to respond with a specific error code to indicate that?

The current behavior seems dangerous to me because it causes data loss and the application is not aware of it.

In regards to buffering requests for several minutes before uploading, is there a defined time interval so that the server guarantees the requests from the same client following such interval be recorded without throughput problem?

Thanks,

**Comment by toru-takahashi** [comment]
@unext-wendong 
Hi, this is Toru, belongs to Treasure Data Support Team.
If you have any questions, please send it to support@treasuredata.com?
Also, if you have any feature requests, please file it on https://feedback.treasuredata.com

We love OSS style, but we would like our customers to contact support team.

**Comment by unext-wendong** [comment]
@toru-takahashi 

Thanks for the response. Yes, I can create a feature request in the feedback portal.

So, at the current point, there is no way for the application to know whether an event has been uploaded successfully or not?

If so, can you clarify it here since there might be other users who are observing the same behavior?

I've been trying to search for related information but couldn't find any, neither from TreasureData's guidelines nor by googling. That's why I came here.

Thanks,

**Comment by unext-wendong** [comment]
Created: https://treasure-data.ideas.aha.io/ideas/INTE-I-214

**Comment by toru-takahashi** [comment]
@unext-wendong 
Yes. there is no way for the application to know whether an event has been uploaded to TreasureData from the endpoint successfully.
So, even if the mobile sdk get 200, there are a possibility to fail to upload data inside of TreasureData due to some validations.
Ex. API KEY validation, time column validation, and so on.

Especially, time column validation;
https://docs.treasuredata.com/articles/javascript-sdk#appendix-api-endpoint
> When you try the above example, please change time value to current unixtime value, we're currently ignoring records which have a timestamp older than 7 days, and newer than 3 days ahead.

**Comment by unext-wendong** [comment]
Thanks for the clarification.

> So, even if the mobile sdk get 200, there are a possibility to fail to upload data inside of TreasureData due to some validations.

Maybe I misunderstood previously, I thought the reason the event wasn't synced to the database was that the endpoint server was too busy and could not handle the requests coming in in short interval. Are you saying it's due to the data validation?

Can you let us know which data validation could be failing in this case? To me, the following two should be fine.
a) The API Key should be fine since both events were using the same key and only one of them got lost.
b) For `postback/v3/event`, the event sent out doesn't contain time column, so it's not because of the time validation.

**Comment by toru-takahashi** [comment]
Could you send it to support@?
We would like to file all support ticket in our support system instead of github.

**Comment by unext-wendong** [comment]
I also reported this to support@treasuredata.com.

However I still feel that it's useful to log this information in a public place so that other users with the same issue can refer to it.

**Comment by unext-wendong** [comment]
Thanks for @toru-takahashi 's help.

Just for logging purpose:
The table records listed in the TreasureData console is only a portion of the actual data. For example, the first 5 records in the list are not necessarily the actual first 5 records in the table, and they might be the actual 1st, 3rd, 4th, 5th and 7th record.

To confirm the events are actually synced to the database, use a query instead.

In my case, the events were actually not being lost. It's only that they were not listed in the console.
