### ISSUE TITLE
Jackson is not suit for Android. Please consider other libraries like gson.

### ISSUE THREAD

**Issue by yanzm** [treasure-data/td-android-sdk#4]
Jackson is large library. It has 7300 methods.
I want to avoid Over 65K Methods problem.
http://developer.android.com/intl/ja/tools/building/multidex.html
Please consider more small library like gson.
https://github.com/google/gson

**Comment by komamitsu** [comment]
That makes sense. I'll take care of it. Thanks!

**Comment by yanzm** [comment]
Thank you.
Please consider also apache commons lang(2396 methods) that used in android-logger-bridge.

**Comment by komamitsu** [comment]
I'm checking the difference of behaviour between Jackson and Gson. Please wait a while.

**Comment by komamitsu** [comment]
I tried to replace Jackson with Gson in https://github.com/treasure-data/td-android-sdk/compare/use_gson branch. But I finally ran into https://github.com/google/gson/issues/692 and this problem can break the compatibility with the existing behaviour of this SDK. I'll take a look at other JSON libraries.

**Comment by komamitsu** [comment]
@yanzm I replaced jackson-databind with jackson-jr and removed commons-lang. As a result, the number of methods decreased from 9700 to 3000. Gson doesn't meet our requirements.

We already released this change as 0.1.7.

**Comment by yanzm** [comment]
Thank you. I'll check it.
